[package]
name = "dtprt_parser_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.18"
reqwest = { version = "0.11.12", features = ["blocking"] }
